database/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//Admin routes
Route::group(['middleware' => 'auth'], function () {

  Route::get('/admin', 'AdminController@index');
  Route::get('/rooms', 'AdminController@rooms');
  Route::get('/report', 'AdminController@report');
  Route::get('/contactus', 'AdminController@contact');
  Route::get('/admin/create', 'AdminController@createUser');
  Route::get('/admin/eidt', 'AdminController@editUser');
  Route::resource('roomType', 'Admin\RoomTypeController')->except('destroy', 'show');
  Route::get('/roomType/delete/{id}', 'Admin\RoomTypeController@delete');
  Route::get('/admin/create', 'AdminController@create');
  Route::post('/admin/save', 'AdminController@save');
  Route::get('/admin/delete', 'AdminController@delete');
  Route::get('/admin/edit/{id}', 'AdminController@edit');
  Route::post('/admin/update/{id}', 'AdminController@update');
  // customer
  Route::resource('customer', 'Admin\CustomersController')->except('destroy', 'show');
  Route::get('/customer/delete/{id}', 'Admin\CustomersController@delete');
  // branch
  Route::resource('branch', 'Admin\BranchController')->except('destroy', 'show');
  Route::get('/branch/destroy/{id}', 'Admin\BranchController@destroy');
  //room
  Route::resource('room', 'Admin\RoomController')->except('destroy', 'show');
  Route::get('/room/delete/{id}', 'Admin\RoomController@delete');
  // payment
  Route::resource('payment', 'Admin\PaymentController')->except('destroy', 'show');
  Route::get('/payment/delete/{id}', 'Admin\PaymentController@delete');
  // payment type
  Route::resource('paymentType', 'Admin\PaymentTypeController');
  Route::get('/paymentType/delete/{id}', 'Admin\PaymentTypeController@delete');
});

Auth::routes();

//Front routes
Route::get('/', 'FrontController@index')->name('home');
Route::get('/home', 'FrontController@index')->name('home');
Route::get('/about', 'FrontController@about');
Route::get('/booking', 'FrontController@booking');
Route::get('/contact', 'FrontController@contact');
Route::get('/career', 'FrontController@career');
Route::get('/career-detail', 'FrontController@careerDetail');
Route::get('/promotion', 'FrontController@promotion');


Route::get('my-users', 'HomeController@myUsers');

database/app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'payment';

    protected $fillable = [
        'amount', 'customerId', 'paymentTypeId', 'paymentDate'
    ];
}

database/app/Models/PaymentType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PaymentType extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'payment_type';

    protected $fillable = [
        'name'
    ];
}

database/app/Http/Controllers/Admin/PaymentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Payment;
use App\Models\PaymentType;
use DB;

class PaymentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $data['payment'] = DB::table('payment')
            ->join('customers', 'payment.id', '=', 'customers.id')
            ->join('payment_type', 'payment.id', '=', 'payment_type.id')
            ->select('payment.*', 'customers.name as customerName', 'payment_type.name as paymentTypeName')
            ->get();
        return view('admin.payment.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $data['paymentType'] = PaymentType::all();
        $data['customers'] = DB::table('customers')->get();
        return view('admin/payment/create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $payment = Payment::create([
            'amount' => $request->amount,
            'customerId' => $request->customerId,
            'paymentTypeId' => $request->paymentTypeId,
            'paymentDate' => $request->paymentDate,
        ]);
        $i = $payment->save();
        if ($i) {
            return redirect()->route('payment.create')
                ->with('success', 'Data has been saved!');
        } else {
            return redirect()->route('payment.create')
                ->with('error', 'Fail to save data!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

database/resources/views/admin/payment/create.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Create Payment</h1>
    <form action="{{route('payment.store')}}" method="POST">
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{url('payment')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          <div>
            {{csrf_field()}}
              <div class="form-group row">
                  <label for="customerId" class="col-sm-4 form-control-label">Customer ID</label>
                  <div class="col-sm-8">
                      <select class="form-control" name="customerId" id="customerId">
                          <option value="">select customer</option>
                          @foreach($customers as $customer)
                              <option id="customerId" name="customerId" value="{{$customer->id}}">{{$customer->name}}</option>
                          @endforeach
                      </select>
                  </div>
              </div>
              <div class="form-group row">
                  <label for="customerId" class="col-sm-4 form-control-label">Payment Type ID</label>
                  <div class="col-sm-8">
                      <select class="form-control" name="paymentTypeId" id="paymentTypeId">
                          <option value="">select payment</option>
                          @foreach($paymentType as $p)
                              <option id="paymentTypeId" name="paymentTypeId" value="{{$p->id}}">{{$p->name}}</option>
                          @endforeach
                      </select>
                  </div>
              </div>
              <div class="form-group row">
                <label for="Name" class="col-sm-4 form-control-label">Amount <span class="text-danger">*</span></label>
                <div class="col-sm-8">
                    <input type="number" class="form-control" id="amount" name="amount" placeholder="Enter your payment amount" value="{{old('amount')}}" required autofocus>
                </div>
              </div>
              <div class="form-group row">
                  <label for="Name" class="col-sm-4 form-control-label">Date <span class="text-danger">*</span></label>
                  <div class="col-sm-8">
                      <input type="date" class="form-control" id="paymentDate" name="paymentDate" value="{{old('paymentDate')}}" required autofocus>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

database/resources/views/admin/payment/edit.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <h1>Edit Payment</h1>
    @foreach ($payment_type as $p)
    <form action="/paymentType/update/<?php echo $payment_type[0]->id; ?>" method="POST">
      <div class="toolbox">
        <button type="submit" name="submit" class="btn btn-oval btn-primary btn-sm">
          <i class="fa fa-save "></i> Save</button>
        <a href="{{url('paymentType')}}" class="btn btn-warning btn-oval btn-sm">
          <i class="fa fa-reply"></i> Back</a>
      </div>
      <br>
      @if(session()->has('success'))
      <div class="alert alert-success">
        {{ session()->get('success') }}
      </div>
      @endif
      @if(session()->has('error'))
      <div class="alert alert-danger">
        {{ session()->get('error') }}
      </div>
      @endif
      <div class="card card-gray" style="padding: 57px">
        <div class="card-block">
          <div class="col-md-6">
            {{csrf_field()}}
            <div class="form-group row">
              <label for="Name" class="col-sm-4 form-control-label">Name <span class="text-danger">*</span></label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter your payment name" value='<?php echo$payment_type[0]->name; ?>' autofocus>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
    @endforeach
  </div>
</section>
@endsection

@section('js')
<script>
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection

database/resources/views/admin/payment/index.blade.php
@extends('layouts.admin')
@section('style')
<style>

</style>
@endsection

@section('content')
<section class="section">
  <div class="container">
    <div class="row" style="margin-bottom: 20px;">
      <div class="col-md-6">
        <h1>Payment</h1>
      </div>
      <div class="col-md-6" style="text-align: right;">
        <a href="{{url('payment/create')}}" class="btn btn-primary btn-sm" title="Create">
          <i class="fa fa-plus"></i> Create
        </a>
      </div>
    </div>
    <table id="example" class="table table-striped table-bordered" style="width:100%">
      <thead>
        <tr>
          <th>Id</th>
          <th>Customer Name</th>
          <th>Payment Type</th>
          <th>Amount</th>
          <th>Payment Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <?php $i = 1; ?>
        @foreach($payment as $p)
        <tr>
          <td>{{$i++}}</td>
          <td>{{$p->customerName}}</td>
          <td>{{$p->paymentTypeName}}</td>
          <td>{{$p->amount}}</td>
          <td>{{$p->paymentDate}}</td>
          <td class="action">
            <a href="{{url('payment/delete?id='.$p->id)}}" class="text-danger" title="Delete"
              onclick="return confirm('Are you sure to delete?')">
              <i class="fa fa-trash"></i>
            </a>
            &nbsp;&nbsp;
            <a  href='payment/edit/{{ $p->id }}' class="text-success">
              <i class="fa fa-edit"></i>
            </a>             
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</section>
@endsection

@section('js')
<script>
  $(document).ready(function() {
    $('#example').DataTable();
  });
  // Disable form submissions if there are invalid fields
  (function() {
    'use strict';
    window.addEventListener('load', function() {
      // Get the forms we want to add validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  })();
</script>
@endsection